[KEYS]
; Go to https://platform.openai.com/account/api-keys to get open ai api key
OPENAI_API_KEY = YOUR_OPENAI_API_KEY
; Go to Contact https://telegram.me/BotFather on telegram to get bot token
TELEGRAM_BOT_TOKEN = YOUR_TELEGRAM_BOT_TOKEN
; the chat ID allowed to update in the json file chat_ids_sfcbot too!!!
CHAT_ID = YOUR_CHAT_ID
; Team_ID (default : 2184)
TEAM_ID = 1234
; league_ID (default : 207)
LEAGUE_ID = 123
; season_ID (default : 2022)
SEASON_ID = 123
; api_football key (free here : https://www.api-football.com/)
API_FOOTBALL_KEY = YOUR_FOOTBALL_KEY