[KEYS]
; Go to https://platform.openai.com/account/api-keys to get open ai api key
OPENAI_API_KEY = your_api_key_here
; Go to Contact https://telegram.me/BotFather on telegram to get bot token
TELEGRAM_BOT_TOKEN = your_bot_token_here
; Team_ID (default : 2184)
TEAM_ID = your_team_id_here
; season_ID (default : 2023)
SEASON_ID = 2023
; api_football key (free here : https://www.api-football.com/)
API_FOOTBALL_KEY = your_api_football_key_here